import { Roboto } from "next/font/google";
import "./globals.css";
import NavBar from "./components/NavBar";


const roboto = Roboto({
  variable: "--font-roboto",
  subsets: ["latin"],
  weight: ["400", "500", "700"], // choose the weights you need
});

export const metadata = {
  title: "Siamsinpawlpi",
  description: "Generated by create next app",
  icons: {
    icon: "/public/Images/sspp-logo.png",
  },
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${roboto.variable} antialiased`}
      >
        <div className="pb-12 lg:pb-20">
        <NavBar />
        </div>
        {children}
      </body>
    </html>
  );
}
